#!/usr/bin/env node
// AUTO-GENERATED by pipeline/agents/scripts/generate-mcp.mjs — do not hand-edit;
// re-run the generator instead so this stays in sync with catalog.json.
//
// MCP server that exposes one tool per entry in ./catalog.json (a snapshot
// of pipeline/03_builds/catalog.json taken at generation time). Each tool
// call pays for itself: POST with no payment -> catch the real x402 v2 402
// challenge (PAYMENT-REQUIRED header) -> sign an EIP-3009
// TransferWithAuthorization with viem using BASE_PRIVATE_KEY -> resubmit
// with the PAYMENT-SIGNATURE header -> return the tool's response to the
// MCP client. No human EVM signature prompt at call time.

import { readFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { CallToolRequestSchema, ListToolsRequestSchema } from "@modelcontextprotocol/sdk/types.js";
import { privateKeyToAccount } from "viem/accounts";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Real x402 v2 transport headers (specs/transports-v2/http.md in
// coinbase/x402) — NOT "X-Signature". Using the wrong header name here would
// silently fail against every real x402 v2 resource server.
const HEADER_PAYMENT = "PAYMENT-SIGNATURE";
const HEADER_PAYMENT_REQUIRED = "PAYMENT-REQUIRED";
const HEADER_PAYMENT_RESPONSE = "PAYMENT-RESPONSE";

const TRANSFER_WITH_AUTHORIZATION_TYPES = {
  TransferWithAuthorization: [
    { name: "from", type: "address" },
    { name: "to", type: "address" },
    { name: "value", type: "uint256" },
    { name: "validAfter", type: "uint256" },
    { name: "validBefore", type: "uint256" },
    { name: "nonce", type: "bytes32" },
  ],
};

function decodeBase64Json(headerValue) {
  try {
    return JSON.parse(Buffer.from(headerValue, "base64").toString("utf8"));
  } catch {
    return null;
  }
}

function randomNonce() {
  const bytes = crypto.getRandomValues(new Uint8Array(32));
  return "0x" + [...bytes].map((b) => b.toString(16).padStart(2, "0")).join("");
}

async function loadCatalog() {
  const raw = await readFile(resolve(__dirname, "catalog.json"), "utf8");
  return JSON.parse(raw);
}

function getAccount() {
  const key = process.env.BASE_PRIVATE_KEY;
  if (!key) {
    throw new Error("BASE_PRIVATE_KEY environment variable is required to pay for x402 tool calls");
  }
  return privateKeyToAccount(key);
}

/**
 * Signs and settles a real x402 EIP-3009 payment for one tool call, then
 * returns the tool's parsed JSON response. Domain (name/version/chainId/
 * verifyingContract) and payTo/amount/nonce window are all taken from the
 * LIVE 402 challenge the server just sent, never from the local catalog
 * snapshot -- catalog.json can go stale, the live challenge cannot.
 */
async function callX402Tool(url, args) {
  const account = getAccount();
  const body = JSON.stringify(args ?? {});
  const headers = { "content-type": "application/json" };

  const firstRes = await fetch(url, { method: "POST", headers, body });
  if (firstRes.status !== 402) {
    if (!firstRes.ok) {
      throw new Error(`tool call failed: HTTP ${firstRes.status}: ${await firstRes.text()}`);
    }
    return await firstRes.json();
  }

  const encodedChallenge = firstRes.headers.get(HEADER_PAYMENT_REQUIRED);
  const challenge = encodedChallenge ? decodeBase64Json(encodedChallenge) : null;
  const requirements = challenge?.accepts?.[0];
  if (!requirements?.scheme || !requirements?.asset || !requirements?.payTo) {
    throw new Error("402 response missing a usable PAYMENT-REQUIRED challenge");
  }

  const chainMatch = /^eip155:(\d+)$/.exec(requirements.network || "");
  if (!chainMatch) {
    throw new Error(`cannot sign for network "${requirements.network}" -- expected CAIP-2 eip155:<chainId>`);
  }
  const chainId = Number(chainMatch[1]);

  const domainName = requirements.extra?.name || "USD Coin";
  const domainVersion = requirements.extra?.version || "2";
  const now = Math.floor(Date.now() / 1000);
  const authorization = {
    from: account.address,
    to: requirements.payTo,
    value: requirements.amount,
    validAfter: "0",
    validBefore: String(now + (requirements.maxTimeoutSeconds || 60)),
    nonce: randomNonce(),
  };

  const signature = await account.signTypedData({
    domain: { name: domainName, version: domainVersion, chainId, verifyingContract: requirements.asset },
    types: TRANSFER_WITH_AUTHORIZATION_TYPES,
    primaryType: "TransferWithAuthorization",
    message: {
      from: authorization.from,
      to: authorization.to,
      value: BigInt(authorization.value),
      validAfter: BigInt(authorization.validAfter),
      validBefore: BigInt(authorization.validBefore),
      nonce: authorization.nonce,
    },
  });

  const paymentPayload = {
    x402Version: challenge.x402Version,
    resource: challenge.resource,
    accepted: requirements,
    payload: { signature, authorization },
    extensions: {},
  };
  const encodedPayment = Buffer.from(JSON.stringify(paymentPayload)).toString("base64");

  const paidRes = await fetch(url, {
    method: "POST",
    headers: { ...headers, [HEADER_PAYMENT]: encodedPayment },
    body,
  });
  if (!paidRes.ok) {
    throw new Error(`paid tool call failed: HTTP ${paidRes.status}: ${await paidRes.text()}`);
  }
  return await paidRes.json();
}

async function main() {
  const catalog = await loadCatalog();

  const server = new Server(
    { name: "x402-mcp-server_by_milza", version: "1.0.0" },
    { capabilities: { tools: {} } },
  );

  server.setRequestHandler(ListToolsRequestSchema, async () => ({
    tools: catalog.map((tool) => ({
      name: tool.slug,
      description:
        `${tool.description} Costs ${tool.priceUsdc} USDC per call on ${tool.network}, paid automatically ` +
        `from BASE_PRIVATE_KEY. Request body fields are tool-specific -- see ${tool.url}/openapi.json.`,
      inputSchema: { type: "object", additionalProperties: true },
    })),
  }));

  server.setRequestHandler(CallToolRequestSchema, async (request) => {
    const { name, arguments: args } = request.params;
    const tool = catalog.find((t) => t.slug === name);
    if (!tool) {
      throw new Error(`unknown tool: "${name}"`);
    }
    const result = await callX402Tool(tool.url, args);
    return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] };
  });

  const transport = new StdioServerTransport();
  await server.connect(transport);
}

main().catch((err) => {
  console.error("[x402-mcp-server_by_milza] fatal:", err instanceof Error ? err.message : err);
  process.exit(1);
});
